import Head from 'next/head'
import { css } from '@emotion/react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p css={testStyle}>テスト</p>
      </main>
    </div>
  )
}

const testStyle = css`
  color: red;
`
